### ISSUE TITLE
Header: social media icons has no space in the right side compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Boynes-Springs#100]
![image](https://cloud.githubusercontent.com/assets/17717843/15423249/27d11eba-1eaf-11e6-9c5b-e831f697f8e2.png)

**Comment by Atcharanak** [comment]
As per design, Logo and contact phone should on the same line.

![image](https://cloud.githubusercontent.com/assets/18587097/15599469/b1d891de-240d-11e6-91fe-f61022a70229.png)
