### ISSUE TITLE
Product listing: Incorrect style of the pagination.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#101]
![image](https://cloud.githubusercontent.com/assets/11186313/15458692/0631ac2a-20d0-11e6-90f4-4c171ab33877.png)

**Comment by Atcharanak** [comment]
Pagination should have style for active as per design.

![image](https://cloud.githubusercontent.com/assets/18587097/15594921/88f1d7c2-23e4-11e6-8cb9-2fe10de19ecc.png)
