### ISSUE TITLE
Product single: There is too less space gap between the featured image and the first row of gallery thumbnails.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#105]
There should be equal space gap between rows and columns.
![image](https://cloud.githubusercontent.com/assets/11186313/15459903/a6efb146-20dc-11e6-8a8b-f2cd166e50f7.png)

**Comment by Atcharanak** [comment]
Issue still happen

NOTE: Size of image was wrong. If the the size is correct, space will be ok.

![image](https://cloud.githubusercontent.com/assets/18587097/15595111/714c41e6-23e6-11e6-8180-1f90a339e385.png)

**Comment by p-wanlaphakorn** [comment]
it's limit just width of image. it's not been fixed
