### ISSUE TITLE
Sidebar form: Button label should read "Send".

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#106]
![image](https://cloud.githubusercontent.com/assets/11186313/15459969/80d51090-20dd-11e6-901d-20b2c62cd55d.png)

**Comment by Atcharanak** [comment]
Style of hover(background color of the button) should be same on the below menu, or not?

![image](https://cloud.githubusercontent.com/assets/18587097/15594521/6f749180-23e0-11e6-94c2-54b3bff9470f.png)

**Comment by p-wanlaphakorn** [comment]
the hover 'send' button is as per home page mock by prefooter design 
![image](https://cloud.githubusercontent.com/assets/18691989/15594843/cfc3f974-23e3-11e6-8142-1b62a2ba5968.png)
