### ISSUE TITLE
News/Services single: Featured image is too small. It is too far from the dimension specified in the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#112]
![image](https://cloud.githubusercontent.com/assets/11186313/15461644/325ec110-20ef-11e6-91b0-1b7331b00e7d.png)

**Comment by Atcharanak** [comment]
Images's size should be 456*342 as per design.

![image](https://cloud.githubusercontent.com/assets/18587097/15594988/35b87d9e-23e5-11e6-81ac-e152677b7581.png)
