### ISSUE TITLE
Home: Video background image is stretched.  Its starting point is at the center when it should be four columns from the right most grid.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#117]
![image](https://cloud.githubusercontent.com/assets/11186313/15766616/1ff5c8f2-2973-11e6-9ff6-226d716f915c.png)

**Comment by p-wanlaphakorn** [comment]
I didn't fix it because the video image should occupy the entire width as per issue #60.

**Comment by roseliesromeo** [comment]
Starting point should be as per suggested in the design.

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/15846694/3c0b411a-2cb2-11e6-8c50-92b59710c329.png)
