### ISSUE TITLE
Banner: Banner text is not centered at lower resolution. Both button and banner text are cut when re-sized to some point.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#119]
![image](https://cloud.githubusercontent.com/assets/11186313/15767084/d4927be4-2977-11e6-8947-7628dba84fc8.png)
![image](https://cloud.githubusercontent.com/assets/11186313/15767164/7ec251de-2978-11e6-9fa1-227bcc9f4f28.png)

**Comment by p-wanlaphakorn** [comment]
it's been fixed at provious issue. 
Could you please try clearing your cache?
