### ISSUE TITLE
W3C error: News Page

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#12]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fboynes-springs.stage.titanweb.com.au%2Fnews%2F

![image](https://cloud.githubusercontent.com/assets/18587097/14847772/b1121c10-0c94-11e6-8ace-1dda21da896c.png)

**Comment by p-wanlaphakorn** [comment]
![image](https://cloud.githubusercontent.com/assets/18691989/15204213/3a29a648-1835-11e6-8d8b-d7cb87ef11c6.png)
