### ISSUE TITLE
Header: Social media will no longer display in 640 resolution and below.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#122]
![image](https://cloud.githubusercontent.com/assets/11186313/15767576/c23f7ee8-297b-11e6-8705-58a998fa2b7d.png)

**Comment by p-wanlaphakorn** [comment]
I fixed it to no display social because the display in 640 resolution is the responsive between col-sm and col-xs.

**Comment by roseliesromeo** [comment]
You may have point but then it's been our standard to display all elements seen in desktop in mobile view. 
Please refer to this site: http://www.pinjarratraders.com.au/

**Comment by p-wanlaphakorn** [comment]
I fixed it. 
but please confirm that the mock in mobile view doesn't have it, it still should have as per standard, right?

**Comment by roseliesromeo** [comment]
yes correct.  It's clearly stated in this standard link:
https://knowledgebase.titanweb.com.au/implementation/mobile-and-browsers/mobile-desktop-sections
