### ISSUE TITLE
Header: Menu is not properly aligned in resolutions below 768.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#126]
![image](https://cloud.githubusercontent.com/assets/11186313/15768112/bbeb0602-2980-11e6-91b9-669175be1c11.png)

**Comment by Atcharanak** [comment]
The arrow should be show, Please fix.

![image](https://cloud.githubusercontent.com/assets/18587097/15815382/e4562eaa-2bf6-11e6-90ea-ce65ec81f711.png)
