### ISSUE TITLE
Home: Video background image is stretched in resolutions 768-991 and 992-1199.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#132]
![image](https://cloud.githubusercontent.com/assets/11186313/15851806/023fabfa-2cd1-11e6-90ae-09360f5ad0c8.png)
![image](https://cloud.githubusercontent.com/assets/11186313/15851856/42e296a4-2cd1-11e6-9998-98985943e816.png)

**Comment by p-wanlaphakorn** [comment]
it's been just fixed in resolution 992-1199 but it can't fix in resolution 768-991 because it need to stretched image for full-width.
