### ISSUE TITLE
W3C error: Wire Forms Page

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#20]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fboynes-springs.stage.titanweb.com.au%2Fproduct-category%2Fwire-forms%2F

![image](https://cloud.githubusercontent.com/assets/18587097/14872341/7a961e62-0d15-11e6-8f7a-9b3d27f6fc7b.png)

**Comment by p-wanlaphakorn** [comment]
![image](https://cloud.githubusercontent.com/assets/18691989/15203265/09c704cc-182c-11e6-8fd1-83b513665dc1.png)
