### ISSUE TITLE
Tablet (Product Category Page): The list of products should be show 3 products in 1 row.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#29]
![image](https://cloud.githubusercontent.com/assets/18587097/14875718/a5312e56-0d37-11e6-8ed6-57d10f6d4069.png)

**Comment by p-wanlaphakorn** [comment]
I've just fixed the width column to default. 
and it's properly 2 columns by default function config of theme. 
please see the fixed below [image attached]

![image](https://cloud.githubusercontent.com/assets/18691989/15279713/8d3d5612-1b51-11e6-9eed-4f4e4ecf944c.png)

**Comment by Atcharanak** [comment]
It's Working fine on vertical view.

But on Landscape view, Layout is not showing properly.

![image](https://cloud.githubusercontent.com/assets/18587097/15346502/fc0b7ed8-1ce2-11e6-94b3-ca1e3aa04054.png)
