### ISSUE TITLE
Videos: Width should be 853px; Height should be 480px in fancy box

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#3]
![image](https://cloud.githubusercontent.com/assets/18587097/14841962/3b87f2fc-0c6d-11e6-8d37-92808704cbb2.png)

**Comment by p-wanlaphakorn** [comment]
it's not fixed. Because the width and height are as per the script js. 
![image](https://cloud.githubusercontent.com/assets/18691989/15102000/77ba979c-15c4-11e6-81eb-4f0d709e9192.png)
