### ISSUE TITLE
Project Scope(Products Listing Page): Products name upto 2 lines.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#33]
![image](https://cloud.githubusercontent.com/assets/18587097/14876575/5be8e3f2-0d40-11e6-97ec-3da1367476b2.png)

**Comment by roseliesromeo** [comment]
Product title is now limited to one line only.  It should allow up to 2 lines and not more than that.

**Comment by Atcharanak** [comment]
Container for title should have the same height.
Example.

![image](https://cloud.githubusercontent.com/assets/18587097/15598087/f3e3065c-2400-11e6-86d5-bc77d954050b.png)
