### ISSUE TITLE
Testimonials Page: Please do not use Lorem ipsum as shown in the design

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#37]
![image](https://cloud.githubusercontent.com/assets/18587097/14878195/2c998dc0-0d4c-11e6-8219-95dc0c29fe27.png)

**Comment by p-wanlaphakorn** [comment]
no content now.
![image](https://cloud.githubusercontent.com/assets/18691989/15134745/43c7f724-1699-11e6-9776-7f9ca44c69ca.png)
