### ISSUE TITLE
Banner: Description isn’t limited to 2 lines as per scope and as implied by the design. In relation to that, the read more button falls down to the lead-in section.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#69]
![image](https://cloud.githubusercontent.com/assets/11186313/14979238/aefad908-1153-11e6-83bd-dcaca294df21.png)
![image](https://cloud.githubusercontent.com/assets/11186313/14979307/18caa052-1154-11e6-9aa0-8829f747954d.png)

**Comment by p-wanlaphakorn** [comment]
fixed
