### ISSUE TITLE
General: Remove outline from all links.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#73]
![image](https://cloud.githubusercontent.com/assets/18587097/15003112/85cecc22-11d2-11e6-9b14-fd4048c2ed8b.png)

**Comment by roseliesromeo** [comment]
Please apply fixes to all clickable elements.
![image](https://cloud.githubusercontent.com/assets/11186313/15458583/a171f0ac-20ce-11e6-9e1d-f14759b8fc83.png)
