### ISSUE TITLE
Banner: Height is too short.  Image is cut.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#81]
![image](https://cloud.githubusercontent.com/assets/11186313/15415277/2bcd6a2c-1e74-11e6-8f1e-d659b696f29e.png)

**Comment by Atcharanak** [comment]
Issue still happen.

![image](https://cloud.githubusercontent.com/assets/18587097/15596438/babd9e28-23f1-11e6-9ee9-1714995a23d6.png)
