### ISSUE TITLE
General pages: Featured image overlaps the page content and beyond the sidebar section.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Boynes-Springs#82]
Sample page: http://boynes-springs.stage.titanweb.com.au/about-us/
![image](https://cloud.githubusercontent.com/assets/11186313/15415430/3f36000a-1e75-11e6-87ed-4864fed0832b.png)

**Comment by Atcharanak** [comment]
Size of images should same on news page.
http://boynes-springs.stage.titanweb.com.au/post-title-goes-two-lines-long3/
