### ISSUE TITLE
Footer: misalignment

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Boynes-Springs#83]
Resolution: 668 to 768 view port

![image](https://cloud.githubusercontent.com/assets/17717843/15418695/8ee57d24-1e93-11e6-93c0-dc90e92ab45a.png)

**Comment by Atcharanak** [comment]
Issue still happen 

![image](https://cloud.githubusercontent.com/assets/18587097/15594868/f5d9b568-23e3-11e6-82af-7de3d664a258.png)
