### ISSUE TITLE
Banner: is not responsive. Please follow the banner implementation of the site sample below

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Boynes-Springs#87]
Sample Site: http://glassblockconstruction-imp.stage.titanweb.com.au/

![image](https://cloud.githubusercontent.com/assets/17717843/15418947/791d7120-1e95-11e6-921f-90e5efa49b2b.png)

**Comment by Atcharanak** [comment]
Issue still happen

Suggestion: The text and buttons are displayed below the banner image for smaller resolution.
Please refer with this website: http://linesent.stage.titanweb.com.au/

**Comment by Atcharanak** [comment]
Please move the text to center of the page.
![image](https://cloud.githubusercontent.com/assets/18587097/15732392/e0b8a97e-28a6-11e6-975d-e73b7c4455f9.png)
