### ISSUE TITLE
Homepage - Welcome Section: featured image is not responsive

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Boynes-Springs#88]
![image](https://cloud.githubusercontent.com/assets/17717843/15419080/2cedfe7c-1e96-11e6-9e64-3f39fc759954.png)

**Comment by Andontae** [comment]
Hi,have a question for this one.

Normally the frontend should be:
- Large device: min-width 1200px
- Medium device: min-width 992px
- Small device: min-width 768px
- Xsmall device: divine screen into 12 piece with same width (base for all devices)
*** the min-width here is the original from bootstrap ***

In PSD, this design is for 768px. But I'm not sure that this is the reasonable design for small device.

If we not check for the width from PSD, what do you think when you first saw this responsive jpg?

**Comment by Atcharanak** [comment]
Suggestion: The video section be displayed at the bottom for 992 and below.

**Comment by Atcharanak** [comment]
Please refer.

if image is at the left, we follow this order image on top and content at the bottom on mobile

if image is at the right hand side, content will be at the top and image at the bottom on mobile

![image](https://cloud.githubusercontent.com/assets/18587097/15732335/7e7818b2-28a6-11e6-892f-7a8c036eb7f0.png)

**Comment by p-wanlaphakorn** [comment]
i don't fixed it.
