### ISSUE TITLE
Contact Us: There is no the text in web copy.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/Boynes-Springs#9]
Please confirm, If it's correct.
![image](https://cloud.githubusercontent.com/assets/18587097/14843617/ee336e28-0c7b-11e6-9625-588c7f2842db.png)

**Comment by p-wanlaphakorn** [comment]
it's correct. The content is from the existing website. 
![image](https://cloud.githubusercontent.com/assets/18691989/15106102/2562274e-15f1-11e6-8a40-f7a3d61d68fe.png)
