### ISSUE TITLE
Services Single: retain the content below the image in 480 and below view port

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Boynes-Springs#92]
![image](https://cloud.githubusercontent.com/assets/17717843/15420001/98b0049c-1e9c-11e6-913a-d8639902082b.png)

**Comment by p-wanlaphakorn** [comment]
I fixed the issue #112 that fixed the size of image and then this issue did not retain the content also.

**Comment by Atcharanak** [comment]
Images should have responsive style.
Images should not be cut for smaller resolution.

![image](https://cloud.githubusercontent.com/assets/18587097/15597719/270aa50c-23fd-11e6-86a8-789afbe06e59.png)
